### ISSUE TITLE
gvh-titlemap parsing error?

### ISSUE THREAD

**Issue by pacohope** [wcbonner/GoveeBTTempLogger#13]
I just downloaded and built the tool on ubuntu 20.10 on a Raspberry Pi 4. If I have no `gvh-titlemap.txt` file in my svg folder, it runs correctly. It downloads data, it writes logs, it creates SVGs, everything's great.

I made a `gvh-titlemap.txt` file that contains the following 2 lines. First one is from the sample file you provide, the other is my own.
```
A4:C1:38:0D:3B:10       H5177 (A4:C1:38:0D:3B:10)
A4:C1:38:49:F7:5A       Humidor (A4:C1:38:49:F7:5A)
```
There is an extra blank line at the end of the file. I invoke the command like this:
`sudo /usr/local/bin/goveebttemplogger -v 2 -l /home/paco/humidor -s /home/paco/humidor`

I see this error output.
```
[2021-02-09T13:52:39] GoveeBTTempLogger Version 2.20210202-1 Built on: Feb  8 2021 at 20:06:08
[2021-02-09T13:52:39] Reading: /home/paco/humidor/gvh-titlemap.txt
[2021-02-09T13:52:39] Reading: /home/paco/humidor/gvh-titlemap.txt
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

I copied your example `gvh-titlemap.txt` unmodified into my directory. Should be harmless (it won't have a title for _my_ device, but that shouldn't matter, right?) I get the same result.

If I remove the file, it runs fine, but if the file is present I get this error.

**Comment by wcbonner** [comment]
I just added a simple check to make the code avoid that error. 

				// rudimentary line checking. It's at least as long as the BT Address and has a Tab character
				if ((TheLine.size() > 18) &&
					(TheLine.find("\t") != std::string::npos))

The lines in the map file will not be ignored if they aren't long enough to include a Bluetooth address and don't have a tab character, which is what I'm using to separate the Bluetooth address from the description.
