### ISSUE TITLE
Simple output?

### ISSUE THREAD

**Issue by sdenike** [wcbonner/GoveeBTTempLogger#25]
Would it be possible to build in the ability to simply output the temp/humidity once in JSON, CSV format and then exit?  I would love to run this via a cron as part of another temperature monitoring script I have. Thanks

**Comment by wcbonner** [comment]
Would the call be to read the existing log file for a particular device, find the most recent data, and output a json string? 

That logic is essentially already done for the MRTG output command, so creating a similar JSON output command would be fairly trivial. 

If you are talking about communicating directly with a device over Bluetooth, that would require significantly more effort as I'm currently only listening for broadcasts from devices and have no guarantee of a broadcast from a device arriving.
