### ISSUE TITLE
Log time format

### ISSUE THREAD

**Issue by mfiano** [wcbonner/GoveeBTTempLogger#52]
Hello, first of all, I want to really thank you for this great piece of software. I needed to upgrade my grow room's environment monitoring, and I picked up 2 H5075's and 3 H5100's. So far, I only got a chance to test out one of the H5075's, but great job!

I spent all day trying to figure out why your software didn't work. `bluetoothctl` would see advertisements from the device, but not the logger. It turns out the signal was just too weak with that ble controller, but with another one they stream in pretty quickly.

Anyway, I just wanted to ask if it is currently possible, or in the works, to have the log written to use the client's local time. Currently I can see times relative to the local time offset. My client is in EDT (GMT -4), but logs are being written with times 4 hours in the future. Additionally, there is no indicator in the timestamp format as to which offset it is using. It's been a couple years since I messed with time conventions, but I think it might make sense to annotate this in the log format if it does not make sense to translate them before writing.

Thanks a lot!

**Comment by wcbonner** [comment]
All log files are in UTC. That way there is no issue with summertime/wintertime issues or logs being combined from different locations and time zones.
